version: '3'
services:
   mysql:
      container_name: mysql
      build: ./mysql
      command: mysqld_safe
   

   laravelfinal:
      container_name: laravel
      build: ./laravel
      working_dir: /home/laravel
      ports:
      - 8001:8000 
      expose:
         - 8000
      depends_on:
      - mysql
      command: php artisan serve --host laravelfinal --port 8000


   nginx:
      container_name: nginx
      build: ./nginx
      ports:
      - 80:80
      depends_on:
         - laravelfinal
        

      command: nginx -g 'daemon off;'
